# Generated by Django 5.1.3 on 2024-11-24 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='componente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='componentes/'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.componente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.venta')),
            ],
        ),
    ]
