# Generated by Django 5.1.3 on 2024-11-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_venta_alter_componente_imagen_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
